### ISSUE TITLE
[Bug] Cannot read property 'accountid' of undefined

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steamstore#23]
error trace:
```
 2018-12-27 | 01:02:30.450 | ERROR | crashBot                       | TypeError: Cannot read property 'accountid' of undefined
    at SteamStore.getAccountData (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steamstore\components\account.js:190:22)
    at syncBarterLibrary (C:\Users\Administrator\OneDrive\Projects\NodeJS\master-bot\index.js:1905:17)
    at appids (C:\Users\Administrator\OneDrive\Projects\NodeJS\master-bot\index.js:953:13)
    at steam.user.getProductInfo (C:\Users\Administrator\OneDrive\Projects\NodeJS\master-bot\index.js:2623:9)
    at C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steam-user\components\apps.js:292:6
    at Object.cb (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steam-user\components\messages.js:174:4)
    at CMClient._netMsgReceived (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:321:26)
    at CMClient.handlers.(anonymous function) (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\Administrator\OneDrive\Projects\NodeJS\node_modules\steam-user\node_modules\steam-client\lib\cm_client.js:305:24)
    at emitOne (events.js:115:13)

```

Related code
```

    function syncBarterLibrary(appids, callback) {
    steam.store.getAccountData((error, ownedApps, ownedPackages) => {
        if (!error && ownedApps.length > 0 && ownedPackages.length > 0) {
            const formdata = {
                bulk_IDs: `app/${ownedApps.join(`,app/`)},sub/${ownedPackages.join(`,sub/`)}`,
                add_IDs: `+ Add IDs`,
                action: `Edit`,
                change_attempted: 1,
                add_from: `IDs`
            };
            httprequest.public.post({
                url: `https://barter.vg/u/my/l/e/`,
                form: formdata
            }, function() {
                if (callback) callback();
            });
        } else if (callback) {
            callback();
        }
    });
    }

```

Again, maybe it's because I have the steam store instance loaded into the steam object?

**Comment by DoctorMcKay** [comment]
Are you logged in (did you set your cookies)?

**Comment by Revadike** [comment]
yes, presumably, but I'll now try to refresh web session prior.
